### ISSUE TITLE
It seems can not load any data?

### ISSUE THREAD

**Issue by DearZack** [amitshekhariitbhu/Android-Debug-Database#12]
I think this project is great, so I write a test app to see it's feature.
I'm sure my phone and my computer are in the same WIFI.
When open the browser, just like this, it has a welcome button, can't see my DB, what's wrong?
![image](https://cloud.githubusercontent.com/assets/17618134/20487002/c840c854-b03c-11e6-98fc-602760b2800a.png)

**Comment by MartinLi2015** [comment]
me to

**Comment by amitshekhariitbhu** [comment]
Which database u r using ?

**Comment by DearZack** [comment]
sqlite

**Comment by bu2zhouzhu** [comment]
@DearZack @MartinLi2015 I guess it's because you're in China. The web page x.x.x.x:8080 will request some files locate in servers some are blocked by China Great Firewall. Like https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js. If you can't open google.com on your computer, you can't see you DB.

**Comment by amitshekhariitbhu** [comment]
New release will work completely offline
