### ISSUE TITLE
Why they cannot communicate by USB？

### ISSUE THREAD

**Issue by DearZack** [amitshekhariitbhu/Android-Debug-Database#4]
Your project is great.
But in my work environment ,it is inconvenience to use wifi.
Why they cannot communicate by USB？

**Comment by amitshekhariitbhu** [comment]
I will add this feature in upcoming release.

Thanks
Amit Shekhar

**Comment by DearZack** [comment]
thanks

**Comment by booknara** [comment]
I agree with this feature. In my company office, I use a wired connection for my laptop and a wireless connection for my test device.

**Comment by amitshekhariitbhu** [comment]
@booknara It works on same Network (Wifi or LAN)

**Comment by booknara** [comment]
@amitshekhariitbhu Thank you for the comment. I know that I can make them to be in the same wireless network. But I prefer using the wired network for the laptop and there is no same wireless network name with wired network. 

Stetho library (made by facebook) that I'm using uses USB connect with chrome://inspect. I haven't checked the Stetho library about how to connect thru USB. 

If your library supports USB, it can be pretty useful.

**Comment by amitshekhariitbhu** [comment]
You are welcome. I will add this feature in upcoming release 👍

**Comment by raizal** [comment]
This is just an alternative suggestion from me for anyone who can't connect from wifi. We'll still able to connect to the page by using usb tethering
192.168.42.129:8080

And for the ADB, because sometimes after using USB Tethering we can't use the ADB over USB again, we need to activate the ADB over network by running this command before activating usb tethering
adb tcpip 5555
After that, after activating USB Tethering, execute this
adb connect 192.168.42.129
Your ADB is active again
